
language: php

php:
    - 5.5
    - 5.6
    - 7.1

services:
    - redis-server

before_install:
    - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
    - composer install -no

script:
    - php ./vendor/bin/phpunit

after_success:
    - curl -s https://codecov.io/bash | bash

notifications:
    email:
        on_success: never
        on_failure: always

